#!/bin/bash
SESSION="TMUX-IDE"

tmux -2 new-session -d -s $SESSION
tmux mouse-select-pane on

tmux new-window -t $SESSION:0
tmux send-keys "cd ~/ && vim" C-m
tmux split-window -h
tmux send-keys "cd ~/" C-m
tmux select-pane -t 1
tmux split-window -v
tmux send-keys "cd ~/" C-m

tmux select-pane -t 0
tmux resize-pane -d 60

tmux new-window -t $SESSION:1 -n "Search"
tmux send-keys "cd ~/src/current/web" C-m

tmux select-window -t 0
tmux rename-window 'Development'

tmux -2 attach-session -t $SESSION
