#!/bin/bash
SESSION="Skytap-IDE"

tmux -2 new-session -d -s $SESSION
tmux mouse-select-pane on

tmux new-window -t $SESSION:0
tmux send-keys "cd ~/src/current/web/ && vim" C-m
tmux split-window -h
tmux send-keys "cd ~/src/wfe_dev/" C-m
tmux send-keys "vagrant ssh"
tmux split-window -h
tmux send-keys "cd ~/src/wfe_dev/ && vagrant up && vagrant ssh && srcwfe && rake service:all:restart && rake service:web:stop && srcweb" C-m
tmux send-keys "bundle exec rails server -p 3000"
tmux select-pane -t 1
tmux split-window -v
tmux send-keys "cd ~/src/current/web/ && hg qseries" C-m

tmux select-pane -t 0
tmux resize-pane -d 60

tmux new-window -t $SESSION:1 -n "Silver Searcher"
tmux send-keys "cd ~/src/current/web" C-m

tmux new-window -t $SESSION:2 -n "Integ SSH"
tmux send-keys "cd ~/src/current/web" C-m

tmux select-window -t 0
tmux rename-window 'Ruby Development'

tmux -2 attach-session -t $SESSION
